### ISSUE TITLE
KDE Plasma Desktop not interactable when plugin installed

### ISSUE THREAD

**Issue by Cate95** [y4my4my4m/kde-shader-wallpaper#46] opened 2024-04-05 13:21 UTC
Not working:
when I install the software I am not able to interact with files and folder which are visible on the Desktop. Also I am not able to interact with widgets or add or remove widgets. It seems that there is a layer on top of the Desktop prohibiting interactions with any desktop clickables. I am able to right click and go to edit mode but I cant get further than this.

Expected behaviour:
Able to interact with Folder and Files which are on the Desktop, as well as beeing able to interact with and add or remove other desktop widgets. 

My Machine: Arch linux, wayland and KDE Plasma.

**Comment by Cate95** [comment] 2024-04-05 13:22
Ah btw. only when I remove the software, I am able to interact with my desktop. adding it again (also when it is not used as a desktop background) it prohibits me to interact with my desktop.

**Comment by Anonymous4045** [comment] 2024-04-05 15:53
I experience the same behavior, with this plasma6 version I can't interact with files on the desktop or drag the mouse to make the blue selection rectangle. I'm running NixOS with Plasma 6.0.3.

**Comment by y4my4my4m** [comment] 2024-04-05 19:18
> Not working: when I install the software I am not able to interact with files and folder which are visible on the Desktop. Also I am not able to interact with widgets or add or remove widgets. It seems that there is a layer on top of the Desktop prohibiting interactions with any desktop clickables. I am able to right click and go to edit mode but I cant get further than this.
> 
> Expected behaviour: Able to interact with Folder and Files which are on the Desktop, as well as beeing able to interact with and add or remove other desktop widgets.
> 
> My Machine: Arch linux, wayland and KDE Plasma.

Somehow I don't experience this, however I believe that [this is the cause](https://github.com/y4my4my4m/kde-shader-wallpaper/blob/0db87022d8578a2e21e3cc5626d6487a0a899d21/package/contents/ui/main.qml#L170-L171).
I'm going to be back home in a few days and I plan to push a fix for that!
Will update you here.

**Comment by resiehnnes** [comment] 2024-04-06 14:45
@y4my4my4m Commenting Component.onCompleted block in main.qml file fixed the problem on my system.

**Comment by y4my4my4m** [comment] 2024-04-09 16:45
@resiehnnes 
should be fixed in the latest release!
https://github.com/y4my4my4m/kde-shader-wallpaper/releases/tag/v3.0.1-plasma6

Please update, restart plasmashell and reopen if it still doesn't work! 
(You need to disable the mouse in the settings, so far no other way around it until I make some C++ wrapper)

**Closed by y4my4my4m** 2024-04-09 16:45 UTC
